# Generated by Django 6.0.7 on 2026-08-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('org_admin', 'Org Admin'), ('qc', 'QC / Test Lead / Tester'), ('dev', 'Developer')], default='qc', max_length=20, verbose_name='Role'),
        ),
    ]
