# Generated by Django 6.0.7 on 2026-08-04 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('key', models.CharField(max_length=20, verbose_name='Project Key')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'project',
                'unique_together': {('tenant', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100, verbose_name='Requirement Ref')),
                ('text', models.TextField(verbose_name='Requirement Description')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Requirement',
                'verbose_name_plural': 'Requirements',
                'db_table': 'requirement',
                'unique_together': {('project', 'ref')},
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Test Case Title')),
                ('precondition', models.TextField(blank=True, default='', verbose_name='Precondition')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20, verbose_name='Priority')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='manual', max_length=20, verbose_name='Source')),
                ('technique', models.CharField(blank=True, max_length=20, null=True, verbose_name='Design Technique')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('requirements', models.ManyToManyField(blank=True, related_name='test_cases', to='testcases.requirement', verbose_name='Linked Requirements')),
            ],
            options={
                'verbose_name': 'Test Case',
                'verbose_name_plural': 'Test Cases',
                'db_table': 'test_case',
            },
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Step Order')),
                ('action', models.TextField(verbose_name='Action')),
                ('expected', models.TextField(verbose_name='Expected Result')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='testcases.testcase', verbose_name='Test Case')),
            ],
            options={
                'verbose_name': 'Test Step',
                'verbose_name_plural': 'Test Steps',
                'db_table': 'test_step',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Suite Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsuites', to='testcases.testsuite', verbose_name='Parent Suite')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Test Suite',
                'verbose_name_plural': 'Test Suites',
                'db_table': 'test_suite',
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.testsuite', verbose_name='Test Suite'),
        ),
    ]
