# Generated by Django 5.2.16 on 2026-08-07 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='requirements/', verbose_name='Requirement Document'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='requirement',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('document', 'Document')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('done', 'Done')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='requirement',
            name='title',
            field=models.CharField(default='Requirement', max_length=255, verbose_name='Requirement Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='testcases.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='ref',
            field=models.CharField(max_length=100, verbose_name='Requirement ID'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Requirement Description'),
        ),
    ]
