# Generated by Django 5.2.16 on 2026-08-12 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0004_testcase_created_at_testcase_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Test Case', 'verbose_name_plural': 'Test Cases'},
        ),
        migrations.AddField(
            model_name='testcase',
            name='case_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Test Case ID'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='estimate_time',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Estimate Time'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='precondition',
            field=models.TextField(blank=True, default='', verbose_name='Preconditions'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='testcases.testsuite', verbose_name='Test Suite'),
        ),
    ]
