# Generated by Django 5.2.16 on 2026-08-13 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0005_alter_testcase_options_testcase_case_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'verbose_name': 'Test Case', 'verbose_name_plural': 'Test Cases'},
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='status',
        ),
        migrations.AddField(
            model_name='testcase',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20, verbose_name='Review Status'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_result',
            field=models.CharField(choices=[('not_run', 'Not Run'), ('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('blocked', 'Blocked')], default='not_run', max_length=20, verbose_name='Test Result'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='precondition',
            field=models.TextField(blank=True, default='', verbose_name='Precondition'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.testsuite', verbose_name='Test Suite'),
        ),
    ]
