# Generated by Django 5.2.16 on 2026-08-13 08:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0006_alter_testcase_options_remove_testcase_case_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testsuite',
            unique_together={('project', 'name')},
        ),
        migrations.AddField(
            model_name='testsuite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsuite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='testcases.testsuite', verbose_name='Test Suite'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suites', to='testcases.project', verbose_name='Project'),
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='parent',
        ),
        migrations.CreateModel(
            name='SuiteTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_suites', to='testcases.testcase')),
                ('test_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_cases', to='testcases.testsuite')),
            ],
            options={
                'db_table': 'suite_test_case',
                'unique_together': {('test_suite', 'test_case')},
            },
        ),
    ]
