# Generated by Django 5.2.16 on 2026-08-13 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0008_alter_testsuite_options_alter_testsuite_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='estimate_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='priority',
            field=models.CharField(choices=[('p1', 'P1 - Critical'), ('p2', 'P2 - High'), ('p3', 'P3 - Medium'), ('p4', 'P4 - Low')], default='p3', max_length=10),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='requirement_ref',
            field=models.CharField(blank=True, default='', help_text='Requirement ID, ví dụ REQ-101', max_length=100),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='test_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suites', to='testcases.project'),
        ),
        migrations.DeleteModel(
            name='SuiteTestCase',
        ),
    ]
