# Generated by Django 5.2.16 on 2026-08-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0009_testsuite_estimate_time_testsuite_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='precondition',
            field=models.TextField(blank=True, default='', verbose_name='Preconditions'),
        ),
    ]
