# Generated by Django 5.2.16 on 2026-08-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0010_testsuite_precondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='assigned_test_cases',
            field=models.ManyToManyField(blank=True, related_name='assigned_suites', to='testcases.testcase', verbose_name='Test Cases'),
        ),
    ]
