# Generated by Django 6.0.7 on 2026-08-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=500, verbose_name='File Path')),
                ('extracted_text', models.TextField(verbose_name='Extracted Text')),
            ],
            options={
                'verbose_name': 'Context Document',
                'verbose_name_plural': 'Context Documents',
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Organization Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('plan', models.CharField(default='free', max_length=50, verbose_name='Plan')),
                ('ai_monthly_quota_usd', models.DecimalField(decimal_places=4, default=10.0, max_digits=10, verbose_name='Monthly AI Quota ($)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenant',
            },
        ),
    ]
