# Generated by Django 5.2.16 on 2026-08-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_update_bug_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='environment',
            field=models.CharField(choices=[('production', 'Production'), ('staging', 'Staging')], max_length=20, verbose_name='Test Environment'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='platform',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('web', 'Web')], max_length=20, verbose_name='Platform'),
        ),
    ]
