# Generated by Django 6.0.7 on 2026-08-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('generate_tc', 'Generate Test Cases'), ('generate_script', 'Generate Test Script'), ('classify_bug', 'Classify Bug Severity')], max_length=30, verbose_name='Job Kind')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20, verbose_name='Status')),
                ('tokens', models.IntegerField(default=0, verbose_name='Tokens Used')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0.0, max_digits=10, verbose_name='Cost ($)')),
                ('output_json', models.JSONField(blank=True, null=True, verbose_name='Output JSON')),
                ('raw_output', models.TextField(blank=True, null=True, verbose_name='Raw Output')),
            ],
            options={
                'verbose_name': 'AI Job',
                'verbose_name_plural': 'AI Jobs',
                'db_table': 'ai_job',
            },
        ),
    ]
