# Generated by Django 6.0.7 on 2026-08-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(verbose_name='Passed')),
                ('duration', models.FloatField(default=0.0, verbose_name='Duration (s)')),
            ],
            options={
                'verbose_name': 'Test Result',
                'verbose_name_plural': 'Test Results',
                'db_table': 'test_result',
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
            ],
            options={
                'verbose_name': 'Test Run',
                'verbose_name_plural': 'Test Runs',
                'db_table': 'test_run',
            },
        ),
        migrations.CreateModel(
            name='TestScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Scenario Name')),
            ],
            options={
                'verbose_name': 'Test Scenario',
                'verbose_name_plural': 'Test Scenarios',
                'db_table': 'test_scenario',
            },
        ),
        migrations.CreateModel(
            name='TestScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(max_length=50, verbose_name='Framework')),
                ('code_content', models.TextField(blank=True, default='', verbose_name='Script Code Content')),
                ('git_path', models.CharField(blank=True, default='', max_length=255, verbose_name='Git Path')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
            ],
            options={
                'verbose_name': 'Test Script',
                'verbose_name_plural': 'Test Scripts',
                'db_table': 'test_script',
            },
        ),
    ]
