# Generated by Django 6.0.7 on 2026-08-04 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scripts', '0001_initial'),
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.testcase', verbose_name='Test Case'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scripts.testrun', verbose_name='Test Run'),
        ),
        migrations.AddField(
            model_name='testscenario',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.testscenario', verbose_name='Test Scenario'),
        ),
        migrations.AddField(
            model_name='testscript',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.testcase', verbose_name='Test Case'),
        ),
    ]
